### PR TITLE
feat: Enable inpainting with the InPaint ControlNet

### PR DESCRIPTION
**Pull request by vzsg**
For this to work, I replaced the ml-stable-diffusion/main dependency with [my fork](https://github.com/vzsg/ml-stable-diffusion/tree/controlnet-inpaint), on a safe branch that was split off from 0.4.0, the last old Xcode-friendly version.

Related: #197, #207.

## Usage

1. Get a ControlNet-capable (`_cn` suffix) model, e.g. [coreml-ghostmix-v20-bakedVAE_cn](https://huggingface.co/coreml/coreml-ghostmix-v20-bakedVAE_cn)
2. Get the InPaint ControlNet model from [ControlNet-Models-For-Core-ML](https://huggingface.co/coreml/ControlNet-Models-For-Core-ML/tree/main/CN), regular or **S**plit**E**insum as you like.
3. Generate or gather an image of the correct size that will be the control image.
4. Open the image in Preview (or an actual image editor), and erase the parts you want infilled to transparent.
5. Save as PNG to keep the alpha channel.
6. Select the models, select this image in Controlnet, adjust prompts if needed, and generate an image.

image

## Example output

|Starting image|CN image (with transparent hole)|Result|
|-|-|-|
|bald man with round face and a goatee sitting at coffee table, camo pa 4225211956 copy|bald man masked transparent|image|

### CODE REVIEW

**Comment by godly-devotion** [comment]
Nice change! Have you tried creating a PR upstream? It would be nicer than to have to maintain our own fork.

**Comment by vzsg** [comment]
I could try, and was considering it, but if they were to merge this into the current main, it would make Mochi only compilable with beta macOS/Xcode.

**Comment by godly-devotion** [comment]
Lets try this. Lets give upstream a few days and see if they are interested in accepting your PR. If not, I'll create a fork and then you can make a PR to it with your changes. That way you'll still keep the credit for the work and I can create a secure fork (not that I believe you'd introduce anything malicious in yours).

**Comment by vzsg** [comment]
That fork would help a lot either way. For example, we could hard-disable the natural language processing parts, so 1.0 will work everywhere, maybe even seeing some improvements.

**Comment by jrittvo** [comment]
My build using 1.0.0 for Sonoma is marginally faster than the present Mochi 4.0 in Ventura, but Mochi 4.0 in Sonoma is also faster.  So the improvement is from Sonoma, not 1.0.0.  But being able to build with a fork of 1.0.0 (with NL removed for now) would open up for tweaks we don't even imagine yet, as vzsg says.

**Comment by atiorh** [comment]
Hello 👋 I just reviewed and tested @vzsg's [PR](https://github.com/apple/ml-stable-diffusion/pull/205) which has a reference to this PR. Thanks for the improvement and I am always open to your feedback on ml-stable-diffusion!

**Comment by vzsg** [comment]
Thank you! 🙇🏻
I'll pitch the more tangible things over ml-stable-diffusion when it's not so late here :)

**Comment by jrittvo** [comment]
Correctly enabling non-square images, getting InPaint working in CN, and making SD-2.1 models usable would be a very nice hat trick!

**Comment by godly-devotion** [comment]
Since this change has been upstreamed, should we close this PR?

**Comment by jrittvo** [comment]
I don't think Mochi will build in code 14.x with ml-stable-diffusion-1.0.0.  That upgrade added in "NaturalLanguage" elements that throw errors unless you are building with Xcode 15 (beta), where they were also added.

So a fork is the only way to add this InPaint mod to Mochi before you start building Mochi with Xcode 15 (like for Sonoma).

**Comment by vzsg** [comment]
Exactly as @jrittvo said. I'm also experimenting with adding more conditional compilation flags to get 1.0 to work with Xcode 14 again, hopefully they'll allow that in as well.

**Comment by jrittvo** [comment]
Is there any way to have Xcode "apply a patch" to a downloaded package dependency before the dependency is used in a build?  From looking at the diffs, your "conditional compilation flags" strategy looks pretty straightforward, but it is still requires quite a bit of work and time spent.  If Apple doesn't bite, it would be a shame if there was no other way to feed the changes to Xcode.  Apple should have kept the "WWDC" update as a branch, leaving 0.4.0 alone, with a plan to merge them sometime in September or October when they release Sonoma.

**Comment by vzsg** [comment]
> Is there any way to have Xcode "apply a patch" to a downloaded package dependency before the dependency is used in a build? From looking at the diffs, your "conditional compilation flags" strategy looks pretty straightforward, but it is still requires quite a bit of work and time spent. If Apple doesn't bite, it would be a shame if there was no other way to feed the changes to Xcode.

There are two valid ways to do that: package editing (which we both were doing to have an editable version of a dependency) and using a fork/branch for the dependency (which is what this PR is). Messing with SPM's processes otherwise, even if technically possible, is something to avoid.

> Apple should have kept the "WWDC" update as a branch, leaving 0.4.0 alone, with a plan to merge them sometime in September or October when they release Sonoma.

I agree 🙁 It would make the transitionary period until Xcode 15 much more comfortable.

**Comment by jrittvo** [comment]
If there isn't a way to get the package editing step included in the Mochi source code, then there isn't a way to distribute those changes cleanly.  The fork/branch seems the only way to do that.

**Comment by vzsg** [comment]
Shots fired: https://github.com/apple/ml-stable-diffusion/pull/208.

**Comment by jrittvo** [comment]
> Shots fired: [apple/ml-stable-diffusion#208](https://github.com/apple/ml-stable-diffusion/pull/208).

Muy elegante!

**Comment by vzsg** [comment]
Superseded by #277.

**Pull request closed without merging**
