### PR TITLE
Sort ControlNet List

### PR DESCRIPTION
**Pull request by jrittvo**
Display list of ControlNet models alphabetically in drop-down menu

### CODE REVIEW

**Comment by godly-devotion** [comment]
Good start! For consistency with the model selector, we could do something like this https://github.com/godly-devotion/MochiDiffusion/pull/127/files

**Comment by jrittvo** [comment]
Gonna take me a bit to grasp what you are getting at, but this is the sort of thing I should be able to figure out with a little help from ChatGPT.  I will dig into it over the weekend.  Thanks for the next step suggestion!

**Comment by jrittvo** [comment]
Updated ControlNet List sort method to match Model List sort method.

**Comment by godly-devotion** [comment]
Looks good, just made some minor changes for completeness. Thanks!

**Pull request merged**
