### PR TITLE
Support Homebrew installation

### PR DESCRIPTION
**Pull request by missuo**
**Support Homebrew installation.**

### CODE REVIEW

**Comment by godly-devotion** [comment]
Does the cask file need to be part of the repo? I personally haven't seen this in other repos.

**Comment by missuo** [comment]
Required. The `.rb` file in the casks directory contains the release information. Brew will find the corresponding release based on this file and install it automatically. 

However, when a new version is released, you may need to manually change the version and sha256 of the `.rb` file, but you can also leave it to GitHub Actions to update it if you want to automate it.

**Comment by vzsg** [comment]
It might also be possible to get included in the [homebrew-casks repo](https://github.com/Homebrew/homebrew-cask/pulls), so this one doesn't need to be aware.

**Comment by missuo** [comment]
> It might also be possible to get included in the [homebrew-casks repo](https://github.com/Homebrew/homebrew-cask/pulls), so this one doesn't need to be aware.

This is of course the better way, but each version update initiates a pr to the `homebrew-casks` repo until it is merged.

**Comment by godly-devotion** [comment]
Honestly since its already available in [homebrew](https://formulae.brew.sh/cask/mochi-diffusion) and Mochi Diffusion has an built-in update checker/updater already, I don't think having the cask version trail behind a few days is terrible.
There's also the fact that I don't want to manage the cask.

**Comment by Mrered** [comment]
Third-party support

```sh
brew tap ivaquero/chinese
brew update
brew install mochi-diffusion
```

**Pull request closed without merging**
