### PR TITLE
Close QuickLook if called for the currently open image

### PR DESCRIPTION
**Pull request by vzsg**
This matches the behavior of QL in other apps, where you can open and close it by repeatedly pressing space.

### CODE REVIEW

**Comment by godly-devotion** [comment]
Interesting, I wonder why setting `quicklookId` works even though it seems its not being used.

**Comment by godly-devotion** [comment]
Never mind I see whats happening.

**Comment by godly-devotion** [comment]
Hmmm it looks that this introduced some regressions.
- Removing another image while Quick Look is open causes Quick Look to close
- If an image is open with Quick Look and is upscaled, the Quick Look view doesn't show the upscaled image but rather closes

**Comment by vzsg** [comment]
Crap... at least both seem easy to reproduce. I'll look into a fix later today.

**Pull request merged**
