### PR TITLE
Allow the Starting Image to be set by drag and drop

### PR DESCRIPTION
**Pull request by gdbing**
fixes: #267 

This PR updates the img2img image well to support drag and drop, like the ControlNet image well already does. It doesn't remove the buttons or change the size of the image well, or any of the layout changes that were discussed in the issue page, it just allows user to drag and drop an image to load it.

Additionally
- I refactored ControlNetView to use the new ImageWellView, instead of duplicating its functionality.
- dragging an image to a well which already has an image now replaces it with the new image, previously the ControlNet image well was disabled once it was loaded with an image

### CODE REVIEW

**Comment by jrittvo** [comment]
A caveat:  There was a period of time in Mochi's development where the user making changes to one parameter (say starting image or model or scheduler) was causing other parameters to change on their own in unwanted ways.  A bug that took a month or two to find and fix.  So any change now to parameter selection (including drag and drop to an image well) will need to be very thoroughly tested before it gets released.  What was happening at that time, by way of example, was that changing the ControlNet model selection kicked out any starting image that had been set.  With no starting image info, the ControlNet model was flying blind.  I may not have it exactly right, but that is the kind of issue we need to make sure does not get introduced as a regression here.

**Comment by jrittvo** [comment]
You can look at the closed PRs for ones about "MainActor" to see what was going on before that I am hoping we don't wake up again with this PR.

**Comment by gdbing** [comment]
I think that Starting Image shouldn't be a problem, because the `startingImage` property is only picked up when `generate()` is called, i.e. when the Generate button is tapped. It isn't used anywhere else, so I don't think that changing it could cause unexpected side effects.

ControlNet is less straightforward to reason about because `setControlNet(CGImage)` calls `loadPipeline()` which modifies state in the `ImageGenerator`, but the new implementation is functionally identical to the old, i.e. calling `setControlNet(CGImage)` when an image is drag and dropped to it.

I've manually tested it by generating an image with consistent parameters and seed and then interrupting at different points ("ready", "loading", and "generating") by dragging and dropping new images to the starting image and control net image wells, and haven't seen any errors or variation in the resulting image. 

Is there a more comprehensive way I should test this?

**Comment by jrittvo** [comment]
Sounds like you've tested it about the same way we have in the past.  I haven't had the chance to do a build with this merged, just not a good time right now, but from the little I understand of Swift, the change to MainActor gave that entity more strength against unexpected overrides.  So that fix was a real fix that should hold up.

**Pull request merged**
