### PR TITLE
Add Chinese README

### PR DESCRIPTION
**Pull request by Jerry23011**
Since the in-app translations are already done, I thought why not do the translations for README as well :)

### CODE REVIEW

**Comment by Jerry23011** [comment]
Sorry about the empty lines, I used Obsidian to edit the `.md` file, it must have made some changes to the spacing.

**Comment by godly-devotion** [comment]
No worries, thanks!

**Comment by Jerry23011** [comment]
Oops! I missed one string. Maybe it would be more convenient for you to make the change, since I'll have to create a new branch then PR. Could you please change **line seven** in `zh-Hans.md`

From `<p align="center">Run Stable Diffusion on Mac natively</p>`

To `<p align="center">在 Mac 上原生运行 Stable Diffusion</p>`

**Comment by godly-devotion** [comment]
Done, thanks!

**Comment by Jerry23011** [comment]
Thank you

**Pull request merged**
