### PR TITLE
fix: set loadModel function as main actor to prevent crash

### PR DESCRIPTION
**Pull request by hoseins77**
In this PR i fixed model loading crash bug. happend on changing model and applying settings.
fixes: #282

### CODE REVIEW

**Comment by jrittvo** [comment]
I then added the add Preview PR #270, with the necessary diff edits to the ImageGenerator.swift file that is changed in both PRs, and everything appears to be working smoothly in another 15 minutes of testing.

There is still the "phantom" duplicate image residual in the Gallery after each new generation completes when Image Preview is enabled.  (A bug I would typically ignore...)

**Comment by godly-devotion** [comment]
I'm a bit cautious of the solution of loading the function in the main thread. I feel like its masking the real issue by forcing it to run the code sequentially. Not to mention this is now blocking the main thread.

**Comment by hoseins77** [comment]
@jrittvo i have fixed preview not desapering problem i will push it soon

**Comment by hoseins77** [comment]
@godly-devotion please check out new changes

**Comment by jrittvo** [comment]
The alternate fix also works consistently in the build I did.

**Comment by vzsg** [comment]
Two sidenotes:
- you should revert the development team change
- there's a typo: `pipline`

**Comment by hoseins77** [comment]
@vzsg Thank you for noticing, i fixed them.

**Comment by godly-devotion** [comment]
Thanks for the changes. I've implemented a fix which fixes the root cause of the crash via 4fe125aa3793d940c4caa293652b39edf5201fd9.

**Comment by jrittvo** [comment]
Is @godly-devotion's fix basically the same as @hoseins77's fix, but applied at a deeper level in the pipeline?  A yes or no answer here is ok for me.

**Comment by hoseins77** [comment]
@jrittvo no i dont think their same. i tried to fix it by changing threads to prevent not available 'self' problem, and @godly-devotion i think fixed it by removing extra function call which caused the crash.

**Pull request closed without merging**
